### PR TITLE
Base changes to upgrade the Java codegenerator for Idris 0.9.19

### PR DESCRIPTION
**Pull request by bgaster**
These changes allow the Java code generator to work with Idris 0.9.19, including support for the new(ish) FFI interface.

It also uses an updated Java runtime, see idris-java-rts.

Include the foundations for a Java package, which currently includes only a base FFI interface.

Included readme with installation instructions and basic usage.

There is still work to be done, most importantly:

  1. adding support for FFI class creation and attribute setting
  2. Regression test suite, probably something simple like what Idris test uses today
  3. Performance test suite, most likely based on https://scalameter.github.io/, because my interest is benchmarking against other JVM languages.

### CODE REVIEW

**Comment by david-christiansen** [comment]
I'm happy to see this getting some activity!

I don't think that there is presently an active maintainer for `idris-java` (I think @JanBessai is doing other things these days), so I'm not sure who the proper merger here is. Since you're interested in it, and you're already doing things like writing thorough docs, would you like the push bit? Also, back when `idris-java` was part of the main Idris repository, large portions of the Idris test suite ran with it in Travis, so it might be worth reviving that as a cheap way to get some basic CI going. Finally, WRT the Maven repo: what do we need to do to take care of that to avoid confusion?

**Comment by bgaster** [comment]
I'm more than happy to have push access.

I should have mentioned that I have been running large parts of the Idris test suite already, although as there is no support for the C FFI this means there are less tests that apply than before. I've not used Travis before but will take a look.

I'm not 100% sure about the MavenRepo, its on my list of actions an will try to come up with a proposal.

**Comment by JanBessai** [comment]
Hi! It is great to see some activity over here :+1: . 
Please hang on while I'll try and evaluate what has to happen to give others access to the maven repository.

**Comment by david-christiansen** [comment]
@JanBessai: Thanks for checking that out! Hope things are good.

@bgaster You can see a template for selective test suite execution [here](https://github.com/idris-lang/Idris-dev/blob/4a1d77ec1004e3c7291a251e737e7b63894a34b5/test/Makefile#L10-L11). You've probably seen that, but I figured it doesn't hurt to drop a link :-) If you'd like help setting up Travis, please let me know.

**Comment by david-christiansen** [comment]
Ok, @bgaster, I've set you up as a member of the `hackers` team in `idris-hackers` and given that team push access to this repo and the RTS repo. Thanks again!

**Comment by JanBessai** [comment]
@bgaster please send me a message or mail with your Sonatype username. Then I can set you up for upload permissions there.

**Comment by bgaster** [comment]
@JanBessai my Sonatype username is bgaster. 

Thanks,

ben

**Comment by JanBessai** [comment]
I've added you to the [project ticket](https://issues.sonatype.org/browse/OSSRH-6667). If I understand correctly that should be enough.

**Pull request merged**
